INSERT INTO TB_USERS (LOGIN, PASSWORD) VALUES ('ADMIN', '$2a$12$Kb/YWYqtQpTPi/hc/Mqi/.Xq4nU4y2A/t4H1z/pTgQ5CDlHno7ORq');

INSERT INTO TB_BENEFICIARIOS (NOME, TELEFONE, DATA_NASCIMENTO, DATA_INCLUSAO) VALUES ('Maria', '(11) 91234-5678', CURRENT_DATE, CURRENT_DATE);
INSERT INTO TB_DOCUMENTOS (TIPO_DOCUMENTO, DESCRICAO, DATA_INCLUSAO, BENEFICIARIO_ID) VALUES ('RG', 'RG numero 11.111.111-1', CURRENT_DATE, 1);
INSERT INTO TB_DOCUMENTOS (TIPO_DOCUMENTO, DESCRICAO, DATA_INCLUSAO, BENEFICIARIO_ID) VALUES ('CPF', 'CPF numero 111.111.111-11', CURRENT_DATE, 1);
